apiVersion: v1
kind: Service              # 1
metadata:
  name: sa-frontend-lb
spec:
  type: LoadBalancer       # 2
  ports:
  - port: {{ .Values.front_end.containerPort }}               # 3
    protocol: TCP          # 4
    targetPort: {{ .Values.front_end.containerPort }}         # 5
  selector:                # 6
    app: {{ .Values.front_end.name }}       # 7