apiVersion: v1
kind: Service
metadata:
  name: sa-web-app-lb
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.sa_web_app.service.port }}
      protocol: TCP
      targetPort: {{ .Values.sa_web_app.containerPort }}
  selector:
    app: {{ .Values.sa_web_app.name }}